### ISSUE TITLE
Integrate Timebar

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-components#1]
- [x] move <a href="https://github.com/GlobalFishingWatch/map-timebar-component">Timebar module</a> here
- [x] deal with specific webpack configuration
- [x] remove timebar repo
- [x] update dependency in <a href="https://github.com/GlobalFishingWatch/data-portal">data portal</a>

**Comment by j8seangel** [comment]
Already on it

**Comment by j8seangel** [comment]
Everything is awesome, everything is cool if you are part of the team.
https://www.youtube.com/watch?v=StTqXEQ2l-Y
