### ISSUE TITLE
Integrate Map

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-components#2]
https://github.com/GlobalFishingWatch/map-client/pull/979

- [x] REDUX_REMOTE_DEBUG env variable
- [x] Remove https://github.com/GlobalFishingWatch/map-colors repo

**Comment by j8seangel** [comment]
We will have to include an ENV variable like `REDUX_REMOTE_DEBUG` to enable remote redux debugging for the module.

It is not been done for now as it has to be included at the project level and doesn't make sense to include it in map-client / data-portal
