### ISSUE TITLE
Some feedback 

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-components#3]
First of all: super nice :) 
This solution looks like the perfect compromise.

A few small comments:
- what is the workflow with `master` / `gh-pages` branches? Would you consider simply using `master` for generating github pages?
- I think `src/component/miniglobe` is not necessary, could be `src/miniglobe`
- We should remove the Usage section on the README as this info is already in `components/index.mdx`
- Rename `/workspace` to  `/sandbox`

TODO:
- [x] Integrate MiniGlobe in 
   - [x] <a href="https://github.com/GlobalFishingWatch/data-portal">data portal</a>
   - [x] <a href="https://github.com/GlobalFishingWatch/map-client">map-client</a>
- [x] remove initial repo 

NEXT UP:
https://github.com/GlobalFishingWatch/map-components/issues/1
https://github.com/GlobalFishingWatch/map-components/issues/2

**Comment by j8seangel** [comment]
I would prefer keep gh-pages as the online version of the documentation apart so this way the master branch is cleaner with library code only.

I like the idea or removing `/components` as it unnecessary, already changed.

Updated Readme with link to documentation

Renamed `workspace` to `sandbox`

**Comment by j8seangel** [comment]
MiniGlobe integrated in data portal, and map-client.

Also, #1 was closed so we could set this as closed and keep working on #2
