### ISSUE TITLE
Rewrite GL style store / Layer Manager brainstorm

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-components#64]
The current `style.actions/reducer` code is too big a monolith, has a lot iterative fixes with a lack of general vision, and has a lot of non orthogonal code. Adding features is difficult and can generate unwanted problems in various parent projects.

Proposed fixes:
- [ ] Rewrite starting with unit tests and a TDD approach. This makes sense as the whole bit merely converts data structures to another data structure.

- [ ] Split actions in several independent action files:
   - [ ] Basemaps (already exists independently)
   - [ ] CARTO context layers: Carto mapconfig management/instanciation
   - [ ] temporal layers: time `filter`, update throttling
   - [ ] custom layers (ie not belonging to the library)
   - [ ] workspace GL layers
   - [ ] upcoming heatmap GL layers

Not 100% sure though. Some layers might be overlapping various types, ie upcoming "animated polygons" layer (both CARTO layer AND temporal). Maybe better approach is a succession of filters activated depending on type fields for every layer.

- [ ] Use reselect to merge layers and apply 
   - [ ] workspace settings (color, opacity, visibility, etc)
   - [ ] layer expressions for hover/select effects

- [ ] Test in sandbox

**Comment by nerik** [comment]
- [ ] Should we keep `style.json`? Split into different JSON files? Have this served on an API endpoint?

**Comment by j8seangel** [comment]
- [ ] Does it worth it to keep using inmutable.js ?

**Comment by nerik** [comment]
- [ ] Modularize

**Comment by nerik** [comment]
Brainstorm 23/01/2020:

- [ ] Generators need documentation
  - [ ] Move library to TS to at least have typedefs
    - [ ] Challenges in term of map-components infrastructure?
    - [ ] Use TSDoc like in `api-client` to document generators input params

- [ ] Error handling: generators should throw when bad inputs are given
  - [ ] We need a **core generator class** that generators extend:
    - [ ] Check inputs (id and type mandatory) when TS typecheck not possible
    - [ ] Manage standard style behaviours : visibility, interactive, selected/highlighted states with default and overrides system
    - [ ] Common utilities set: color handling/conversion

- [ ] **InteractionManager** as done in the Books project:
  - [ ] Based on LayerManager input parameters
  - [ ] Responsible for generation of `interactiveLayerIds`
  - [ ] Handles feature interaction priority
  - [ ] Prepares popup data in a standard way
  - [ ] Overwrites style generated by LM depending on `selectedFeatures` and `highlightedFeatures` for each layer?
  - [ ] Manages map cursor states?
  - [ ] Handles cluster interactivity? (ie zoom to zoom level X when feature is clustered, do whatever when feature is not clustered)

- [ ] **LegendManager** / **Legend component**
  - [ ] Reads standardized legend data generated by LayerManager in map style

**Comment by j8seangel** [comment]
Moved to https://github.com/GlobalFishingWatch/frontend/issues/11
