### ISSUE TITLE
Less aggressive test suite commit hook

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-components#88]
Test suite is running at each commit, when it covers only a very small part of the codebase. Could we have it look only at staged files like the linter?

**Comment by nerik** [comment]
Or moving the hook to `prepublish` ?

**Comment by j8seangel** [comment]
pre-publish is not a git hook so we can't use the current tools to do that, what about pre-push ? or we could use this: https://github.com/typicode/pkg-ok

**Comment by j8seangel** [comment]
good idea, it was done here: https://github.com/GlobalFishingWatch/map-components/commit/72676e8d5d2bb279b324ef3fd513b3b76a9b6fd6

**Comment by nerik** [comment]
Thanks!
